DjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site_app/', include('site_app.urls'))
]

site_app/urls.py
from django.urls import path
from . import views

app_name = "site_app"

urlpatterns = [
    path('home/', views.home, name = 'home'),
    path('research/', views.research, name = 'research'),
    path('publications/', views.publications, name = 'publications'),
    path('team/', views.team, name = 'team')
]

site_app/models.py
from django.db import models

# Create your models here.

site_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request, 'site_app/home.html')

def research(request):
    return render(request, 'site_app/research.html')

def publications(request):
    return render(request, 'site_app/publications.html')

def team(request):
    return render(request, 'site_app/team.html')

site_app/templates/site_app/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<title>Kelvin Lab</title>

<style>
    .image-container {
        flex: 1;
        text-align: right;
        padding: 10px;
    }
    .image-rwa-container {
        flex: 1;
        text-align: center;
        padding: 10px;
    }
    
    
</style>

<div class="text-box">
    <p><b><u>Infectious diseases account for about 1/3 of all deaths worldwide.</b></u> 
        <br>
        <br>
        The majority of these are in developing countries where children are at the highest risk. Furthermore infectious pathogens directly or indirectly lead to the development of 1/3 of all cancers. Dr. David Kelvin’s research team conducts studies to identify pathogenic mechanisms of immune evasion and disease severity in ancient infectious diseases, infectious emerging diseases, and cancer development.

        Dr. Kelvin has an internationally based research program and carries out studies in Shantou (China), Sardinia (Italy), Kigali (Rwanda), and Halifax (Canada). His central research programs include Ancient Pathogens, Cancer and Infectious Disease, and Emerging and Re-emerging Infectious Diseases. 
        <br>
        Dr. Kelvin has published in several high impact journals including Nature, Science, Nature Medicine, Nature Immunology, New England Journal of Medicine as well as several open access journals. Dr. Kelvin and several international colleagues established the Journal of Infection in Developing Countries (JIDC), an open access journal devoted to infectious diseases in resource limited countries.
        </p>
</div>
<div class="image-rwa-container">
    
    <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/rwa1.jpeg" alt="Rwa1" width="250" height="200">
    <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/rwa2.jpeg" alt="Rwa2" width="250" height="200">
    <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/rwa3.png" alt="Rwa3" width="250" height="200">
</div>




{% endblock %}

site_app/templates/site_app/publications.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
<title>Publications</title>
<div style="text-align: center;">
    <p><b>As a way to promote scientific transparency, all of our work is published in open-access journals.</b></p>
</div>

<ul>
    <li><p>Kumar A, Dutt M, Dehury B, Sganzerla Martinez G, Swan CL, Kelvin A, Richardson C, Kelvin DJ.  <br>
        Inhibition potential of natural flavonoids against selected omicron (B.1.19) mutations in the spike receptor binding domain of SARS-CoV-2: a molecular modeling approach.<br>
        Journal of Biomolecular Structure and Dynamics 2023. 
         <a href = "https://doi.org/10.1080/07391102.2023.2291165" target="_blank">[Link] </a></p> </li>
<li><p>Karuhije J, Nkeshimana M, Zakham F, Hewins B, Rutayisire J, Sganzerla Martinez G, Kelvin DJ, Ndishimye P <br>
    Understanding knowledge, attitudes and practices on Ebola Virus Disease: a multi-site mixed methods survey on preparedness in Rwanda.<br>
    BMC Public Health, 2023, (23) 2417. 
     <a href = "https://doi.org/10.1186/s12889-023-17251-w" target="_blank">[Link] </a></p> </li>

<li><p>Sganzerla Martinez G, Dutt M, Kumar A, Kelvin DJ. <br>
    PoxiPred: An artificial intelligence-based method for the prediction of potential antigens and epitopes to accelerate vaccine development efforts against poxviruses.<br>
    (PREPRINT) Biorxiv (2023) <a href = "https://www.biorxiv.org/content/10.1101/2023.08.04.551871v1" target="_blank">[Link] </a></p> </li>

<li><p>Sganzerla Martinez G, Kelvin DJ. <br> 
    Convergence in Mobility DataSets from Apple, Google, and Meta.<br> 
    JMIR Public Health and Surveillance, 2023;9:e44286.
    <a href = "https://publichealth.jmir.org/2023/1/e44286" target="_blank">[Link]</a></p></li>

<li><p> Dutt M, Kumar A, Rout M, Dehury B, Sganzerla Martinez G, Ndishimye P, Kelvin AA, Kelvin DJ.<br>
    Drug repurposing for Mpox: Discovery of small molecules as potential inhibitors against DNA-dependent RNA polymerase using molecular modeling approach.<br> 
    Journal of Cellular Biochemistry, 2023, 24:701-715.  
    <a href = "https://onlinelibrary.wiley.com/doi/10.1002/jcb.30397" target="_blank">[Link]</a></p></li>

<li><p>Sganzerla Martinez G, Hewins B, LeBlanc JJ, Ndishimye P, Ostadgavahi AT, Kelvin DJ. <br>
    Evaluating the effectiveness of lockdowns and restrictions during SARS-CoV-2 variant waves in the Canadian province of Nova Scotia.<br> 
    Frontiers in Public Health, 2023, 11.
    <a href = "https://www.frontiersin.org/articles/10.3389/fpubh.2023.1142602/full" target="_blank">[Link]</a></p></li>

<li><p>Shukla R, Chandra A, Kumar A, Kandpal P, Avashthi H, Goel VK, Qamar I, Singh N, Kelvin DJ, Singh TR.<br> 
    Repurposing of drugs against methyltransferase as potential Zika virus therapies<br> 
    Scientif Reports 2023, 13 (7870).
    <a href = "https://www.nature.com/articles/s41598-023-33341-6" target="_blank">[Link]</a></p></li>  

<li><p>Garduno A, Sganzerla Martinez G, Ostadgavahi AT, Kelvin DJ, Cusack R, Martin-Loeches I. <br>
    Parallel Dysregulated Immune Response in Severe Forms of COVID-19 and Bacterial Sepsis via Single-Cell Transcriptome Sequencing.<br> 
    Biomedicines 2023, 11(3).
    <a href = "https://www.mdpi.com/2227-9059/11/3/778" target="_blank">[Link]</a></p></li>

<li><p>Sganzerla Martinez G, Ostadgavahi AT, Mahmud-Al-Rafat A, Garduno A, Cusack R, Bermejo-Martin JF, Martin-Loeches I, Kelvin DJ. <br>
    Model-interpreted outcomes of artificial neural networks classifying immune biomarkers associated with severe infections in ICU.<br> 
    Frontiers in Immunology, 2023, 14.
    <a href = "https://www.frontiersin.org/articles/10.3389/fimmu.2023.1137850/full" target="_blank">[Link]</a></p></li>

<li><p>Shukla R, Kumar A, Kelvin DJ, Singh TR.<br> 
    Disruption of DYRK1A-induced hyperphosphorylation of amyloid-beta and tau protein in Alzheimer’s disease: An integrative molecular modeling approach.<br> 
    Frontiers in Molecular Biosciences, 2023, 9.
    <a href = "https://www.frontiersin.org/articles/10.3389/fmolb.2022.1078987/full" target="_blank">[Link]</a></p></li>

<li><p>Sganzerla Martinez G, Garduno A, Mahmud-Al-Rafat A, Ostadgavahi AT, Avery A, de Avila e Silva S, Cusack R, Cameron C, Cameron M, Martin-Loeches I, Kelvin DJ. <br>
    An artificial neural network classification method employing longitudinally monitored immune biomarkers to predict the clinical outcome of critically ill COVID-19 patients.<br> 
    PeerJ, 2022, 10:e14487.
    <a href = "https://peerj.com/articles/14487/" target="_blank">[Link]</a></p></li>

<li><p>Kumar A, Sharma M, Richardson CD, Kelvin DJ. <br> 
    Potential of Natural Alkaloids From Jadwar (Delphinium denudatum) as Inhibitors Against Main Protease of COVID-19: A Molecular Modeling Approach<br> 
    Frontiers in Molecular Biosciences, 2022, 9.
    <a href = "https://www.frontiersin.org/articles/10.3389/fmolb.2022.898874/full" target="_blank">[Link]</a></p></li>

<li><p>Hewins B, Rahman M, Bermejo-Martin JF, Kelvin AA, Richardson CD, Rubino S, Kumar A, Ndishimye P, Ostadgavahi AT, Mahmud-Al-Rafat, A, Kelvin DJ.<br> 
    Alpha, Beta, Delta, Omicron, and SARS-CoV-2 Breakthrough Cases: Defining Immunological Mechanisms for Vaccine Waning and Vaccine-Variant Mismatch.<br> 
    Frontiers in Virology, 2022, 2.
    <a href = "https://www.frontiersin.org/articles/10.3389/fviro.2022.849936/full" target="_blank">[Link]</a></p></li>
</ul>


{% endblock %}

site_app/templates/site_app/research.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<title>Research</title>

<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Wildlife Surveillance
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>Wildlife is a reservoir for infectious agents</strong><br>
          A natural hotspot for agents that cause infectious diseases is the wildlife. For better monitoring potential changes in wildlife that may cause potential spillover events, we have partnered up with institutions in Eastern Africa to perform field work in collecting samples and immunizing animals. Currently, we have active work being done in <b>Rwanda</b> and <b>Democratic Republic of the Congo</b>.<br>
          Samples are constantly collected and investigated to observe if there are any ongoing signals of infection in cattle, sheep, and goats. We make use of state-of-the-art technology such as Artificial Intelligence and Single Cell RNA-sequencing to perform these investigations
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Drug Repurposing
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>We are interested in drug discovery and repurposing by leveraging computational techniques to analyze biological data.</strong><br>
           First, our pipelines facilitate the identification of potential drug targets, prediction of drug interactions, and understanding the underlying molecular mechanisms of diseases. In addition, our bioinformatics pipelines contribute to drug repurposing by exploring existing drugs for new indications based on their known biological activities.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            Early Diagnostic Tools
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>We can use Artificial Intelligence to predict the outcome of patients</strong><br>
          Artificial Intelligence (AI) can find hidden patterns in complex data. We have partnered up with hospitals in <b>Ireland </b>, <b>Spain </b>, and <b>USA </b> to obtain samples from patients undergoing dysregulated immune responses caused by infectious agents. After processing these samples in our laboratory facilities, we quantify the amount of circulatory level of proteins of interest and expression level of certain genes. AI helps us to use the collected data to come up with predictions on outcome and level of severity of patients.
        </div>
      </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
            Bioinformatics Tools
          </button>
        </h2>
        <div id="collapseFour" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>We are constantly creating new tools to assist a wide range of biologists.</strong><br> 
            The need for tailored bioinformatics pipelines arises when processing biological data decreases in costs. With this in mind, our lab is constantly creating new tools to assist different professionals of the life sciences to better extract meaningful information on their data. By having an open-source development mind, all of our tools are freely accessible.
          </div>
        </div>
      </div>
  </div>

{% endblock %}

site_app/templates/site_app/team.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Our Team</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                margin: 0;
                padding: 0;
            }
    
            header {
                background-color: #F0F8FF; /* Alice Blue */
                color: #333;
                text-align: center;
                padding: 1em;
            }
    
            .team-section {
                display: flex;
                flex-wrap: wrap;
                justify-content: center;
                padding: 2em;
            }
    
            .team-member {
                position: relative;
                width: 300px;
                margin: 1em;
                background-color: #fff;
                border: 1px solid #ddd;
                border-radius: 8px;
                overflow: hidden;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                cursor: pointer;
            }
    
            .team-member img {
                width: 100%;
                height: 300px;
                object-fit: cover;
            }
    
            .member-details {
                padding: 1em;
            }
    
            h3, p {
                margin: 0;
            }
    
            .popup-box {
                display: none;
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background: rgba(0, 0, 0, 0.5);
                justify-content: center;
                align-items: center;
            }
    
            .popup-content {
                background: #fff;
                padding: 20px;
                border-radius: 8px;
                position: relative;
            }
    
            .close-btn {
                position: absolute;
                top: 10px;
                right: 10px;
                cursor: pointer;
            }
        </style>
    </head>
{% extends 'base.html' %}

{% load static %}

{% block content %}
<body>

    <div style="text-align: center;">
        <p><b>Our amazing team</b></p>
    </div>
    <!-- First Team Member Section -->
    <section class="team-section">
        <!-- PI -->
        <div class="team-member" onclick="showPopup('David J Kelvin', 'Principal Investigator', 'david.kelvin@dal.ca', 'May the Force be with you.')">
            <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/pic_david.avif" alt="pic_david">
            <div class="member-details">
                <h3>David J Kelvin</h3>
                <p>Principal Investigator</p>
            </div>
        </div>
    </section>

        <!-- Postdocs -->
    <section class="team-section">

        <div class="team-member" onclick="showPopup('Anuj Kumar', 'Postdoctoral Researcher', 'KumarAnuj@dal.ca', 'Anuj is a passionate bioinformatician deeply involved in screening potential therapeutics for emerging infectious diseases. He excels in utilizing high-throughput data, employing cutting-edge computational methods to drive insights for effective treatment development.')">
            <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/pic_anuj.jpeg" alt="pic_anuj">
            <div class="member-details">
                <h3>Anuj Kumar</h3>
                <p>Postdoctoral Researcher</p>
            </div>
        </div>
        <div class="team-member" onclick="showPopup('Gustavo Sganzerla Martinez', 'Postdoctoral Researcher', 'gustavo.sganzerla@dal.ca', 'Gustavo sits on the very intersection of a Venn diagram in which one side is biology and the other is computer programming.')">
            <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/pic_gustavo.JPG" alt="pic_gustavo">
            <div class="member-details">
                <h3>Gustavo Sganzerla Martinez</h3>
                <p>Postdoctoral Researcher</p>
            </div>
        </div>
        <div class="team-member" onclick="showPopup('Pacifique Ndishimye', 'Research Associate and Project Coordinator', 'pacifique.ndishimye@dal.ca', 'Pacifique’s primary research areas of focus include Global health, Climate-sensitive disease, Outbreaks, Host-pathogen interaction, predictive analytics, and immunology.')">
            <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/pic_pacifique.jpg" alt="pic_pacifique">
            <div class="member-details">
                <h3>Pacifique Ndishimye</h3>
                <p>Research Associate and Project Coordinator</p>
            </div>
        </div>
    </section>

        <!-- Grad Students -->
    <section class="team-section">
        <div class="team-member" onclick="showPopup('Ali Toloue', 'PhD Candidate', 'ali.toloue@dal.ca', 'Ali is a PhD student, bridging the gap between host immune response in ICU patients and the transformative power of data science and genomics in understanding sepsis and COVID-19.')">
            <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/pic_ali.jpg" alt="pic_ali">
            <div class="member-details">
                <h3>Ali Toloue</h3>
                <p>PhD Candidate</p>
            </div>
        </div>

        <div class="team-member" onclick="showPopup('Benjamin Hewins', 'Masters Candidate', 'benjamin.hewins@dal.ca', 'Ben is most interested in understanding how characteristics of human health act as predictors of infectious disease outcome.')">
            <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/pic_ben.jpg" alt="pic_ben">
            <div class="member-details">
                <h3>Benjamin Hewins</h3>
                <p>Masters Candidate</p>
            </div>
        </div>

        <div class="team-member" onclick="showPopup('Brigitte Umutoni', 'PhD Candidate', 'bribrimuto@gmail.com', 'Brigitte is passionate about engaging in research, specifically within the fields of epidemiology and public health. Her motivation stems from the desire to contribute to improving the life of people through a multidisciplinary approach.')">
            <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/pic_brigitte.jpeg" alt="pic_brigitte">
            <div class="member-details">
                <h3>Brigitte Umutoni</h3>
                <p>PhD Candidate</p>
            </div>
        </div>

        
    </section>

        <!-- Others -->
    <section class="team-section">
        <div class="team-member" onclick="showPopup('Mansi Dutt', 'Bioinformatics Especiallist', 'mansidutt@dal.ca', 'Mansi, a computational biologist, specializes in analyzing molecular-level biological data using bioinformatics tools like Bulk RNA-Seq and Single-cell sequencing, with a primary focus on CADD for screening potential inhibitors against emerging diseases.')">
            <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/pic_mansi.png" alt="pic_mansi">
            <div class="member-details">
                <h3>Mansi Dutt</h3>
                <p>Bioinformatics Especialist</p>
            </div>
        </div>

        <div class="team-member" onclick="showPopup('Nikki Kelvin', '-', 'jane@example.com', '')">
            <img src="member2.jpg" alt="Team Member 2">
            <div class="member-details">
                <h3>Nikki Kelvin</h3>
                <p>-</p>
            </div>
        </div>

        <div class="team-member" onclick="showPopup('Patricia Kelvin', 'Humanitarian Projects Director', 'trishkelvin@gmail.com', 'Patricia is a director of humanitarian projects. Her work includes both ongoing and emergency support to communities and individuals in need.')">
            <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/trish_pic.jpeg" alt="pic_trish">
            <div class="member-details">
                <h3>Patricia Kelvin</h3>
                <p>Humanitarian Projects Director</p>
            </div>
        </div>
    </section>


    <!-- Popup Box -->
    <div id="popupBox" class="popup-box" onclick="hidePopup()">
        <div class="popup-content" onclick="event.stopPropagation();">
            <span class="close-btn" onclick="hidePopup()">&times;</span>
            <h3 id="popupName"></h3>
            <p id="popupPosition"></p>
            <p id="popupEmail"></p>
            <p id="popupBio"></p>
            <button class="close-btn" onclick="hidePopup()">Close</button>
        </div>
    </div>

    <script>
        function showPopup(name, position, email, bio) {
            document.getElementById('popupName').innerText = name;
            document.getElementById('popupPosition').innerText = 'Position: ' + position;
            document.getElementById('popupEmail').innerText = 'Email: ' + email;
            document.getElementById('popupBio').innerText = bio;
            document.getElementById('popupBox').style.display = 'flex';
        }

        function hidePopup() {
            document.getElementById('popupBox').style.display = 'none';
        }
    </script>
</body>
</html>
{% endblock %}

templates/base.html
{% load static %}

<style>
.colored-background {
    background-color: #F0F8FF;
    padding: 10px; 
  }

  
  .text-box {
    border: 1px solid #000;
    padding: 12px;
    width: 100%;
    line-height: 1.5;
    text-align: justify;
    max-width: 1650px; 
  }

  small {
    font-size: 80%; /* Adjust the percentage as needed */
    line-height: 1; /* Adjust the line height as needed */
}

.your-container p {
    margin-bottom: 6px; /* Adjust the value as needed */
  }


            .popup-box_contact {
                display: none;
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background: rgba(0, 0, 0, 0.5);
                justify-content: center;
                align-items: center;
            }
    
            .popup-content_contact {
                background: #fff;
                padding: 20px;
                border-radius: 8px;
                position: relative;
            }
    
            .close-btn {
                position: absolute;
                top: 10px;
                right: 10px;
                cursor: pointer;
            }



</style>
  


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous">
</script>
<script src="https://kit.fontawesome.com/d4ed401b86.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="master_bts_forms.css">


<nav class="navbar avbar-light navbar-expand-lg" style="background-color: #F0F8FF;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'site_app:home'%}">Kelvin Lab</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav align-items-start"> <!-- Use align-items-start class -->
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'site_app:research'%}">Research</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'site_app:publications'%}">Publications</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'site_app:team'%}">Team</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Tools
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="https://mproteinprofiler.microbiologyandimmunology.dal.ca" target="_blank">Multiple Protein Profiler</a></li>
                        <li><a class="dropdown-item" href="https://aw.iimas.unam.mx/cdbprom/index.php" target="_blank">Comprehensive Directory of Bacterial Promoters</a></li>
                       
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" onclick="showPopup_contact('Dalhousie University', 'David Kelvin Lab','5850 College Street 10A|Halifax|NS|B3H4H7', 'email@id.com')">Contact</a>
                </li>
            </ul>
        </div>
        <div class="image-container ms-auto">
            <a href = 'https://www.dal.ca' target = "_blank">
            <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/dal.png" alt="Dal Logo" width="75" height="75">
            </a>
        </div>
    </div>
</nav>

 


  <div class="colored-background">
    <h2>Laboratory of Emerging Infectious Diseases</h2>
    <a><b>Dalhousie University</a></b>
    <br>
    <a>Department of Microbiology & Immunology</a>
  </div>

  <body style="display: flex; flex-direction: column; min-height: 100vh;">
    

    <div class="flex-grow-1">
      {% block content %}
      
      {% endblock %}
    </div>
  
  
    <footer class="bg-secondary text-black text-center" style="background-color: #F0F8FF !important;">
        <a href = "https://www.dal.ca" target = "_blank">
        <img src="https://raw.githubusercontent.com/gustavsganzerla/lab-website/main/site_app/static/images/dal_fm2.png" alt="Dal Logo FM" width="300" height="130">
        </a>
        <div class="your-container">
            <p>Department of Microbiology & Immunology</p>
            <p>Laboratory of Emerging Infectious Diseases</p>
            
          </div>

           
    </footer>
    
    <!-- Popup Box -->
 <div id="popupBox_content" class="popup-box_contact" onclick="hidePopup_contact()">
    <div class="popup-content_contact" onclick="event.stopPropagation();">
        <span class="close-btn" onclick="hidePopup_contact()">&times;</span>
        <h3 id="popupInstitution"></h3>
        <p id="popupLab"></p>
        <p id="popupAddress"></p>
        <p id="popupEmail_2"></p>
        
        <button class="close-btn" onclick="hidePopup_contact()">Close</button>
    </div>
</div>

<script>
    function showPopup_contact(institution, lab, address, email) {
        document.getElementById('popupInstitution').innerText = institution;
        document.getElementById('popupLab').innerText = lab;
        document.getElementById('popupAddress').innerText = address;
        document.getElementById('popupEmail_2').innerText = email;
        document.getElementById('popupBox_content').style.display = 'flex';
    }

    function hidePopup_contact() {
        document.getElementById('popupBox_content').style.display = 'none';
    }
</script>
</body>